-- Add the 'editor' role: a freelance editor account scoped to the Edit Tracker.
--
-- user_roles.role has carried a CHECK constraint of ('admin','staff','client')
-- since 20260619000001, so Settings → Team could not write the new role at all
-- without this — the insert would fail with a constraint violation.
--
-- Nothing else changes at the database level. Since 20260706000002 the tracker's
-- tables (jobs, job_todos, organizations) are governed by "authenticated" RLS
-- policies rather than per-role ones, so an editor already has exactly the
-- database access they need to move cards; what an account may *reach* is
-- enforced in the app (src/lib/roles.ts), same as for staff and client.
--
-- Constraint names are generated by Postgres for inline CHECKs, so the old one
-- is looked up by the column it guards rather than assumed to be
-- user_roles_role_check.

DO $$
DECLARE
  con RECORD;
BEGIN
  FOR con IN
    SELECT c.conname
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'public'
      AND t.relname = 'user_roles'
      AND c.contype = 'c'
      AND pg_get_constraintdef(c.oid) ILIKE '%role%'
  LOOP
    EXECUTE format('ALTER TABLE public.user_roles DROP CONSTRAINT %I', con.conname);
  END LOOP;

  ALTER TABLE public.user_roles
    ADD CONSTRAINT user_roles_role_check
    CHECK (role IN ('admin', 'staff', 'client', 'editor'));
END $$;
